# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import dlt
from pyspark.sql import functions as F

# =========================
# BRONZE
# =========================

@dlt.table(
    name="bronze_customers",
    comment="Capa bronze de clientes desde samples.bakehouse.sales_customers"
)
def bronze_customers():
    return spark.table("samples.bakehouse.sales_customers")


@dlt.table(
    name="bronze_franchises",
    comment="Capa bronze de franquicias"
)
def bronze_franchises():
    return spark.table("samples.bakehouse.sales_franchises")


@dlt.table(
    name="bronze_suppliers",
    comment="Capa bronze de proveedores"
)
def bronze_suppliers():
    return spark.table("samples.bakehouse.sales_suppliers")


@dlt.table(
    name="bronze_sales_transactions",
    comment="Capa bronze de transacciones"
)
def bronze_sales_transactions():
    return spark.table("samples.bakehouse.sales_transactions")


@dlt.table(
    name="bronze_reviews_chunked",
    comment="Capa bronze de reviews chunked"
)
def bronze_reviews_chunked():
    return spark.table("samples.bakehouse.media_gold_reviews_chunked")
