# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

# =========================
# GOLD - DIMENSIONES
# =========================
import dlt
from pyspark.sql import functions as F
@dlt.table(
    name="dim_customers",
    comment="Dimensión de clientes"
)
def dim_customers():
    df = dlt.read("silver_customers")
    return (
        df.select(
            "customer_id",
            "full_name",
            "email",
            "phone",
            "address",
            "city",
            "state",
            "country",
            "continent",
            F.col("postal_zip_code").alias("zip_code"),
            "gender"
        ).dropDuplicates(["customer_id"])
    )


@dlt.table(
    name="dim_franchises",
    comment="Dimensión de franquicias"
)
def dim_franchises():
    df = dlt.read("silver_franchises")
    return (
        df.select(
            "franchise_id",
            "franchise_name",
            "city",
            "district",
            F.col("zipcode_str").alias("zipcode"),
            "country",
            "size",
            "longitude",
            "latitude",
            "supplierID"
        ).dropDuplicates(["franchise_id"])
    )


@dlt.table(
    name="dim_suppliers",
    comment="Dimensión de proveedores"
)
def dim_suppliers():
    df = dlt.read("silver_suppliers")
    return (
        df.select(
            "supplier_id",
            "supplier_name",
            "ingredient",
            "continent",
            "city",
            "district",
            "size",
            "longitude",
            "latitude",
            "approved_flag"
        ).dropDuplicates(["supplier_id"])
    )
