# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

# =========================
# GOLD - HECHOS
# =========================
import dlt
from pyspark.sql import functions as F
@dlt.table(
    name="fact_sales_transactions",
    comment="Hecho de ventas enriquecido con dimensiones"
)
def fact_sales_transactions():
    tx = dlt.read("silver_sales_transactions")
    dim_c = dlt.read("dim_customers")
    dim_f = dlt.read("dim_franchises")
    dim_s = dlt.read("dim_suppliers")

    fact = (
        tx
        .join(dim_c, "customer_id", "left")
        .join(dim_f, "franchise_id", "left")
        .join(dim_s, dim_f.supplierID == dim_s.supplier_id, "left")
    )

    return fact.select(
        "transaction_id",
        "date",
        "time",
        "dateTime",
        "customer_id",
        "franchise_id",
        "supplier_id",
        "product",
        "quantity",
        "unitPrice",
        "totalPrice",
        "paymentMethod",
        "card_hash"
    )

